@id = LoI7UgLGn0m-Rs1k3pZpTQ
@baseUrl = http://localhost:7089/api

GET {{baseUrl}}/series
Content-Type: application/json

###

GET {{baseUrl}}/{{id}}
Content-Type: application/json

###

POST {{baseUrl}}/series
Content-Type: application/json

{
  "title": "Cloud",
  "description": "All cloud posts"
}

###

PUT {{baseUrl}}/series/{{id}}
Content-Type: application/json

{
  "title": "Cloud",
  "description": "All posts related to Azure Cloud"
}


###

DELETE {{baseUrl}}/series/{{id}}
Content-Type: application/json
