@MarkdownBlog.Functions_HostAddress = http://localhost:7119
@seriesId = mL7bN1IJqEGe9nTempMETA
@authorId = 8o-sQOeCrUCJ2RxcKzax6g
@postId = g7PfYC6ycE2hC1TUTd5bCQ

GET {{MarkdownBlog.Functions_HostAddress}}/api/series

###

GET {{MarkdownBlog.Functions_HostAddress}}/api/series/{{seriesId}}

###
POST {{MarkdownBlog.Functions_HostAddress}}/api/series
Content-Type: application/json

{
  "title": "Cloud",
  "description": "All cloud posts"
}

###

PUT {{MarkdownBlog.Functions_HostAddress}}/api/series/{{seriesId}}

Content-Type: application/json

{
  "title": "Cloud",
  "description": "All cloud posts"
}
###

DELETE {{MarkdownBlog.Functions_HostAddress}}/api/series/{{seriesId}}

### 

## Authors Endpoints ###

GET {{MarkdownBlog.Functions_HostAddress}}/api/authors

###
GET {{MarkdownBlog.Functions_HostAddress}}/api/authors/{{authorId}}

###

POST {{MarkdownBlog.Functions_HostAddress}}/api/authors
Content-Type: application/json

{
  "Name": "John Doe",
  "ImageUri": "https://media.licdn.com/dms/image/C4E03AQFMupIkLM-_6w/profile-displayphoto-shrink_800_800/0/1516337443631?e=1692230400&v=beta&t=l13Ddl6Cs9i79PJqj1pFQSm6gn4QfR8x6KFuPkY1OE4",
  "Bio": "Coder, Surfer"
}
###

PUT {{MarkdownBlog.Functions_HostAddress}}/api/authors/{{authorId}}
Content-Type: application/json

{
  "Name": "John Doe",
  "ImageUri": "https://media.licdn.com/dms/image/C4E03AQFMupIkLM-_6w/profile-displayphoto-shrink_800_800/0/1516337443631?e=1692230400&v=beta&t=l13Ddl6Cs9i79PJqj1pFQSm6gn4QfR8x6KFuPkY1OE4",
  "Bio": "Coder, Surfer, Golfer",
  "Id": "8H2ut3lxn0yQaxefos988g"
}

###

DELETE {{MarkdownBlog.Functions_HostAddress}}/api/authors/{{authorId}}

### POSTS ENDPOINTS

GET {{MarkdownBlog.Functions_HostAddress}}/api/posts

###

GET {{MarkdownBlog.Functions_HostAddress}}/api/posts/{{postId}}

###

POST {{MarkdownBlog.Functions_HostAddress}}/api/posts
Content-Type: application/json

{
    "title": "Fifth Post Title",
    "bannerUri": "https://picsum.photos/1000/300",
    "description": "Subtext",
    "body": "This is my fifth blog post.",
    "authorIds": [
        "95TCdmnA3UuApj9wVP54yw"
    ],
    "series" : {
        "id": "1",
        "title": "Blog Series",
        "description": "This is a Blog Series"
    },
    "meta": {
        "contentType": 1,
        "contentLocation": "../../md-posts/sample.md"
    }
}

###

DELETE {{MarkdownBlog.Functions_HostAddress}}/api/posts/{{postId}}
Content-Type: application/json

