# For more info on HTTP files go to https://aka.ms/vs/httpfile

GET https://localhost:7299/api

###

POST https://localhost:7299/author
Content-Type: application/json

{
  "name": "amit",
  "imageUri": "myimage",
  "bio": "bionic"
}
