0# For more info on HTTP files go to https://aka.ms/vs/httpfile

GET https://localhost:7299/api

###

GET https://localhost:7299/api/author
Content-Type: application/json

###

GET https://localhost:7299/api/author/C-DUBfBOh0W66uqMkybTVQ
Content-Type: application/json

###

POST https://localhost:7299/api/author
Content-Type: application/json

{
  "name": "amit philips",
  "imageUri": "myimage",
  "bio": "bionic"
}

###

PUT https://localhost:7299/api/author/C-DUBfBOh0W66uqMkybTVQ
Content-Type: application/json

{
  "name": "amit philips",
  "imageUri": "myimage",
  "bio": "bionic"
}


###

DELETE https://localhost:7299/api/author/C-DUBfBOh0W66uqMkybTVQ
Content-Type: application/json
