@id = g7PfYC6ycE2hC1TUTd5bCQ

GET https://localhost:7299/api/posts
Content-Type: application/json

###

GET https://localhost:7299/api/posts/{{id}}
Content-Type: application/json

###

POST https://localhost:7299/api/posts
Content-Type: application/json

{
    "title": "Fourth Post Title",
    "bannerUri": "https://picsum.photos/1000/300",
    "description": "Subtext",
    "body": "This is my fourth blog post.",
    "authorIds": [
        "1"
    ],
    "series" : {
        "id": "1",
        "title": "Blog Series",
        "description": "This is a Blog Series"
    },
    "meta": {
        "contentType": 1,
        "contentLocation": "../../md-posts/sample.md"
    }
}

###

DELETE https://localhost:7299/api/posts/Ji8kJNKu4USnoEw_51lG8Q
Content-Type: application/json